name: ab-dev
channels:
- conda-forge
dependencies:
- python=3.11
- click
- rich
- pyyaml
- pip:
  - mkdocs-glightbox
  - pyyaml_env_tag

- black
- coverage
- mypy
- mkdocs-material
- pytest
# For MyPy
- types-pyyaml
