name: ab-dev
channels:
- conda-forge
dependencies:
- click
- click-aliases
- pip
- python=3.12
- pyyaml
- requests
- rich
- pip:
  - mkdocs-glightbox
  - mkdocs-kroki-plugin
  - pyyaml_env_tag

- bandit
- black
- coverage
- graphviz
- mkdocs-graphviz
- mkdocs-material
- mypy
- pytest
# For MyPy
- types-pyyaml
