name: ab-dev
channels:
- conda-forge
dependencies:
- click
- humanize
- pip
- python=3.13
- pyyaml
- requests
- rich
- pip:
  - click-aliases
  - mkdocs-glightbox
  - mkdocs-kroki-plugin
  - pyyaml_env_tag

- bandit
- coverage
- graphviz
- mkdocs-graphviz
- mkdocs-material
- mypy
- pytest
- pre-commit
# For MyPy
- types-pyyaml
- types-requests
