name: ab-dev
channels:
- conda-forge
dependencies:
- python=3.11
- click
- requests
- rich
- pyyaml
- pip:
  - mkdocs-glightbox
  - mkdocs-kroki-plugin
  - pyyaml_env_tag

- bandit
- black
- coverage
- mypy
- mkdocs-material
- mkdocs-graphviz
- grapviz
- pytest
# For MyPy
- types-pyyaml
