dev_addr: localhost:7000
site_name: GNSS-Process Automation with Bernese GNSS Software
site_description:
site_author: Joachim Mortensen

repo_name: AutoBernese
repo_url: https://github.com/SDFIdk/AutoBernese

nav:
- Home: index.md
- User manual:
  - Install AutoBernese: manual/install-autobernese.md
  - Quick start: manual/quick-start.md
  - Command-line reference: manual/command-reference.md
  - Configuration files: manual/configuration-files.md
  - Download sources: manual/download-sources.md
- Development:
  - Contribute: dev/contribute.md
  - System overview: dev/system-overview.md
- Prerequisites: prerequisites.md
- References: references.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png

  language: en
  features:
  - navigation.sections
  - navigation.expand
  - navigation.top

extra_css:
- stylesheets/extra.css
- stylesheets/asciinema-player.css

extra_javascript:
- javascript/asciinema-player.min.js

plugins:
- search
- glightbox
- kroki:
    FileTypes:
    - png
    - svg
# - mkdocs-asciinema

markdown_extensions:
- admonition
- attr_list
- footnotes
- toc:
    permalink: true

- pymdownx.arithmatex:
    generic: true

- pymdownx.betterem:
    smart_enable: all

# Make admonitions collapsable with ??? instead of !!!
- pymdownx.details

- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg

- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite

- pymdownx.keys

- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
- pymdownx.snippets

- mkdocs_graphviz
- md_in_html