station:

  sites_needed: [
    # IGS
    OSLS, STAS, SMID, SULD,
    BUDP, BOR1, MAR6, ONSA,
    POTS, RIGA, SPT0, VIS0,
    WSRT, WTZR,

    # Local
    ESBC, ESBH, FER5, FYHA,
    GESR, HABY, HIRS, SMI2,
    SUL5, TEJH, MOJN, BUDD,
    SKEJ, RIKO, FYNO, ESH5,
    GREJ
  ]

  # Til STA
  IGS_stations:
  - ABCD
  - EFGF

  # Til STA
  COR_stations:
  - sadf
  - fdsa

bpe:

  tasks:

  - name: NOTHING
    task:
      # !BPETask
      pcf_file: NOTHING
      bpe_campaign: EXAMPLE
      year: '2019'
      session: '0440'
      sysout: NOTHING
      status: NOTHING.RUN
      taskid: NOTHING

# data:

  # sources:

  # - !Source
  #   name: RINEX data
  #   url: fff
  #   destination: !Path [*CAMPAIGN, '{campaign.year}']
  #   parameters:
  #     date: !DateRange
  #       beg: 2023-01-01
  #       end: 2023-01-02
