name: Publish docs via GitHub Pages
on:
  push:
    branches:
    - main

  pull_request:
    paths:
    - 'docs/**'
    - 'mkdocs.yml'


jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install MkDocs and dependencies
        run: pip install mkdocs-material mkdocs-glightbox mkdocs-kroki-plugin mkdocs-graphviz

      - name: Build and deploy documentation to official documentation website
        if: github.event_name == 'push'
        run: mkdocs gh-deploy --force

      - name: Build documentation to retrieve artifacts
        if: github.event_name != 'push'
        run: mkdocs build
