name: Run tests

on: [push, pull_request]

jobs:

  test:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash -l {0}

    steps:

    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          environment-file: environment-dev.yml
          auto-activate-base: false
          activate-environment: brahmath-dev

    - name: Install test dependencies
      run: python -m pip install -e .

    - name: Test
      run: pytest
